title: "Eudaimonia IP / UDIP Consult"
description: "Innovation strategy, IP intelligence, and PatAxial consulting."
url: "https://nuancenil.github.io"   # ← 個人帳號網址
baseurl: "/udipconsult"               # ← 專案路徑
permalink: /:categories/:year/:month/:day/:title/
email: "genius@eudaimonia-ip.com"
lang: zh
plugins:
  - jekyll-feed
  - jekyll-seo-tag

brand_color: "#1f3b63"
accent_color: "#3e6ea1"
muted_color: "#6b7280"
light_bg: "#f8fafc"
