title: "Eudaimonia IP / UDIP Consult"
description: "Innovation strategy, IP intelligence, and PatAxial consulting."
url: "https://nuancenil.github.io"
baseurl: "/udipconsult"

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

email: "service@eudaimonia-ip.com"
lang: zh

plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: null
logo: "/assets/images/logo.png"

brand_color: "#B6C6CF"
accent_color: "#D47854"
text_color: "#47423F"
background_color: "#EEEFEF"
muted_color: "#A09D95"

timezone: Asia/Taipei
future: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# 保留這行確保 _data/nav.yml 等被讀取
data_dir: _data

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _site
  - .github
